network:
  version: 2
  ethernets:
    enp0s3:
      renderer: NetworkManager
      match: {}
      dhcp4: true
      networkmanager:
        uuid: "1eef7e45-3b9d-3043-bee3-fc5925c90273"
        name: "VirtualBox-NAT"
        passthrough:
          connection.timestamp: "1784130218"
          ipv6.method: "disabled"
          ipv6.ip6-privacy: "-1"
          proxy._: ""
